title: "Gustavo Vilca"
description: "Sociólogo. Coordinador de GI sociedad, política y gobierno.  Profesor en UNAJ."
url: "https://gustavovilca.github.io"

theme: minima
author: GLVC

sass:
  style: compressed
minima:
  custom_css:
    - assets/css/custom.css

header_pages:
  - index.md
  - about.md
  - research.md
  - teaching.md
  - outreach.md
  - blog.md
  - notas.md
  - ideas.md
