title: "Gustavo Vilca"
name: "Gustavo Vilca"
description: "Investigador en gestión pública y transformación universitaria"
url: "https://gustavovilca.github.io"

theme: minima

author: Gustavo Vilca

