title: "Gustavo Vilca"
description: "Sociólogo. Coordinador de GI sociedad, política y gobierno.  Profesor en UNAJ."
url: "https://gustavovilca.github.io"

theme: minima
author: GLVC


header_pages:
  - index.md
  - investigacion.md
  - docencia.md
  - incidencia.md
  - ideas.md
  - acerca de.md
